apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: student-deployment 
  labels: 
    app: student 
spec: 
  replicas: 3 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: student 
  template: 
    metadata: 
      name: student-template
      labels: 
        app: student 
    spec: 
      containers:
        - name: student-container
          image: 262349351040.dkr.ecr.ap-south-1.amazonaws.com/studentapp
          ports:
            - name: student-port
              containerPort: 8080
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"


          